hook_add = '''
" Python
let g:python_highlight_all = 1
" python.vim
let python_highlight_all = g:python_highlight_all

" Vim
let g:vimsyntax_noerror = 1
let g:vim_indent_cont = 0

" Java
let g:java_highlight_functions = 'style'
let g:java_highlight_all=1
let g:java_highlight_debug=1
let g:java_allow_cpp_keywords=1
let g:java_space_errors=1
let g:java_highlight_functions=1

" Markdown
" http://mattn.kaoriya.net/software/vim/20140523124903.htm
let g:markdown_fenced_languages = [
  \  'coffee',
  \  'css',
  \  'erb=eruby',
  \  'javascript',
  \  'js=javascript',
  \  'json=javascript',
  \  'ruby',
  \  'sass',
  \  'xml',
  \  'vim',
  \]

" Tex
let g:tex_flavor = 'latex'

" Folding
let g:tex_fold_enabled = 1
let g:xml_syntax_folding = 1
let g:php_folding = 1
let g:perl_fold = 1

" Update filetype.
" autocmd MyAutoCmd BufWritePost * nested |
"   \ if &l:filetype ==# '' || exists('b:ftdetect')
"   \   unlet! b:ftdetect |
"   \ filetype detect |
"   \ endif
'''


[ftplugin]

_ = '''
  " Disable automatically insert comment.
  " setl formatoptions-=ro | setl formatoptions+=mMBl
  setl formatoptions-=j
  setl formatoptions-=ro
  setl formatoptions+=Bnlq

  " Disable auto wrap.
  if &l:textwidth != 70 && &filetype !=# 'help'
    setlocal textwidth=0
  endif

  " " Use FoldCCtext().
  " if &filetype !=# 'help'
  "   setlocal foldtext=FoldCCtext()
  " endif
'''

html = '''
setlocal includeexpr=substitute(v:fname,'^\\/','','')
setlocal path+=./;/
'''

php = 'setlocal path+=/usr/local/share/pear'

go = '''
highlight default link goErr WarningMsg
match goErr /\<err\>/
'''

vim = '''
if 5000 < line('$')
  syntax sync minlines=200
endif
'''

qfreplace = 'setlocal nofoldenable'

toml = 'syntax sync minlines=500'

ruby = '''
setlocal omnifunc=
'''
