[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = '<Plug>'
on_cmd = ['VimShell', 'VimShellTab', 'VimShellExecute', 'VimShellPop', 'VimShellInteractive']

[[plugins]]
repo = 'ujihisa/vimshell-ssh'
on_ft = 'vimshell'


#unite

[[plugins]]
repo = 'rhysd/unite-ruby-require.vim'
on_source = 'unite.vim'
on_ft= 'ruby'

[[plugins]]
repo = 'basyura/unite-rails'
on_source = 'unite.vim'
on_ft = 'ruby'


#view

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'
hook_add = '''
  let g:vinarise_enable_auto_detect = 1
'''

[[plugins]]
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
on_ft = 'markdown'
hook_add = '''
  " " 設定されてると非同期にならない
  " if executable('firefox')
  "   let g:previm_open_cmd='firefox'
  " endif
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
on_cmd = ['IndentLinesToggle', 'LeadingSpaceToggle']
hook_add = '''
  let g:indentLine_enabled              = 0
  let g:indentLine_faster               = 1
  let g:indentLine_showFirstIndentLevel = 1
  let g:indentLine_color_term           = 208
  nmap <silent>\tl :IndentLinesToggle<CR>
'''

[[plugins]]
repo = 't9md/vim-quickhl'
on_map = ['<Plug>(quickhl', '<Plug>(operator-quickhl']

[[plugins]]
repo = 'oblitum/rainbow'
on_cmd = ['RainbowToggle', 'RainbowLoad']
hook_add = '''
  let g:rainbow_ctermfgs = ['blue', 'green', 'yellow', 'magenta', 'red', 'darkmagenta', 'darkblue', 'darkgreen', 'darkcyan']
'''

[[plugins]]
repo = 'lilydjwg/colorizer'
on_cmd = ['ColorClear', 'ColorToggle', 'ColorHighlight']
hook_add = '''
  let g:colorizer_nomap   = 1
  let g:colorizer_startup = 0
  nmap \hz <Plug>Colorizer
'''


#action

[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_cmd = 'Linediff'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = ['<Plug>(EasyAlign)', '<Plug>(LiveEasyAlign)']
hook_source = 'source ~/.vim/rc/easyalign.rc.vim'

[[plugins]]
repo = 'AndrewRadev/switch.vim'
on_cmd = 'Switch'
on_map = '!'
hook_source = 'source ~/.vim/rc/switch.rc.vim'

[[plugins]]
repo = 'osyo-manga/vim-jplus'
on_map = '<Plug>(jplus'

[[plugins]]
repo = 'terryma/vim-expand-region'
on_map = ['<Plug>(expand_region_expand)', '<Plug>(expand_region_shrink)']

[[plugins]]
repo     = 'dhruvasagar/vim-table-mode'
on_map   = ['<Plug>(table-mode', '\tm', '\tt']
on_cmd   = ['TableModeToggle', 'Tableize']
hook_add = '''
  let g:table_mode_map_prefix = '\t'
  let g:table_mode_corner = '|'
  xmap \tT <Plug>(table-mode-tableize-delimiter)
'''

#search and replace

[[plugins]]
repo = 'haya14busa/vim-asterisk'
on_map = '<Plug>(asterisk-'

[[plugins]]
repo = 'tpope/vim-abolish'
on_map = ['<Plug>Coerce']
hook_add = '''
  let g:abolish_no_mappings = 1
  nmap sc <plug>Coerce
'''

[[plugins]]
repo = 'osyo-manga/vim-hopping'
on_map = '<Plug>(hopping'

[[plugins]]
repo = 'daisuzu/rainbowcyclone.vim'
on_map = ['<Plug>(rc_search_', '<Plug>(rc_highlight)']

[[plugins]] # quickfixの各行を編集、反映できる
repo = 'thinca/vim-qfreplace'
on_ft = ['unite', 'quickfix']


#ruby

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
if = "!has('nvim')"
on_ft = 'ruby'
hook_add = '''
  let g:ruby_hl_lvar_hl_group = 'rubyLocalVariable'
  au u10ac ColorScheme * hi rubyLocalVariable ctermfg=38
'''

#python

[[plugins]]
repo = 'davidhalter/jedi-vim'
if = "!has('nvim')"
on_ft = 'python'
hook_source = '''
  let g:jedi#smart_auto_mappings = 0
  let g:jedi#completions_enabled = 0
  let g:jedi#auto_vim_configuration = 0
  let g:jedi#show_call_signatures = 1
  let g:jedi#show_call_signatures_delay = 200
'''

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = 'python'
hook_add = '''
  let g:autopep8_ignore = 'E221,E261,E302,E303,F401'
  let g:autopep8_max_line_length = 200
'''

#haskell
[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'
external_commands = 'ghc-mod'


#input

# [[plugins]]
# repo = 'rsense/rsense'
# name = 'orig_rsense'
# on_ft = 'ruby'
#
# [[plugins]]
# repo = 'NigoroJr/rsense'
# on_ft = 'ruby'

# [[plugins]]
# repo = 'osyo-manga/vim-monster'
# on_ft = 'ruby'
# hook_add = '''
#   let g:monster#completion#rcodetools#backend = "async_rct_complete"
# '''

[[plugins]]
repo = 'justmao945/vim-clang'
if = "!has('nvim')"
on_ft = ['c', 'cpp']
hook_source =  '''
  let g:clang_c_options = '-std=gnu11'
  let g:clang_cpp_options = '-std=c++1z'
  let g:clang_c_completeopt = &completeopt
  let g:clang_cpp_completeopt = &completeopt
  let g:clang_auto = 0
  let g:clang_diagsopt = ''
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_ft = 'snippet'
on_event = 'InsertEnter'

[[plugins]]
repo = 'mattn/googlesuggest-complete-vim'
on_event = 'InsertEnter'
hook_add = 'set completefunc=googlesuggest#Complete'


#git

[[plugins]]
repo = 'lambdalisue/vim-gista'
on_cmd = ['Gista']
on_func = 'gista#'

[[plugins]]
repo = 'lambdalisue/vim-gita'
on_cmd = ['Gita']

[[plugins]]
repo = 'mattn/gist-vim'
depends = 'webapi-vim'
on_cmd = 'Gist'
hook_source = '''
  let g:gist_clip_command = 'xclip -selection clipboard'
'''

#web

[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = [ 'OpenBrowser', 'OpenBrowserSearch', 'OpenBrowserSmartSearch' ]
on_map = [ '<Plug>(openbrowser-open)', '<Plug>(openbrowser-search)', '<Plug>(openbrowser-smart-search)', '<Plug>(openbrowser-wwwsearch)' ]
on_func = 'openbrowser#'

[[plugins]]
repo = 'tyru/open-browser-github.vim'
depends = 'open-browser.vim'
on_cmd = ['OpenGithubFile', 'OpenGithubIssue', 'OpenGithubPullReq' ]

[[plugins]]
repo = 'mattn/excitetranslate-vim'
on_cmd = ['ExciteTranslate', 'Trans']
hook_add = '''
  xnoremap gst :ExciteTranslate<CR>
'''
hook_source = '''
  command! -range Trans :<line1>,<line2>:ExciteTranslate

  autocmd BufNewFile ==Translate==* call s:trans_config()
  function! s:trans_config() abort
    setl nobuflisted
    nnoremap q :bd<CR>
  endfunction
'''


#tags and ref

[[plugins]] # Ruby/Bundlerに対応して、必要最低限のtagsのみを非同期生成
repo = 'alpaca-tc/alpaca_tags'
depends = 'vimproc.vim'
on_cmd = ['AlpacaTagsBundle', 'AlpacaTagsUpdate', 'AlpacaTagsEnable', 'AlpacaTagsSet', 'AlpacaTagsCleanCache', 'AlpacaTagsDisable', 'AlpacaTagsKillProcess', 'AlpacaTagsProcessStatus']


#operator

[[plugins]] # se evaluate textobj as expression of lambda of ruby
repo = 'rhysd/vim-operator-evalruby'
depends = 'vim-operator-user'
on_map = '<Plug>(operator-evalruby)'

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp']
hook_add = '''
  let g:clang_format#command = 'clang-format'
  " au u10ac FileType c,cpp map <buffer>= <Plug>(operator-clang-format)
'''

[[plugins]] # <space>j <space>k
repo = 'osyo-manga/vim-operator-jump_side'
depends = 'vim-operator-user'
on_map  = '<Plug>(operator-jump'


#misc

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = '<Plug>'
on_path = '.*'
hook_source = 'source ~/.vim/rc/vimfiler.rc.vim'

[[plugins]]
repo = 'sudo.vim'
on_cmd = ['SudoWrite', 'SudoRead']
hook_add = '''
  command! Sw silent SudoWrite %
'''

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = ['UndotreeToggle', 'UndotreeShow']

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoToggle', 'GundoShow']

[[plugins]]
repo = 'rbtnn/vimconsole.vim'
on_cmd = ['VimConsoleOpen', 'VimConsoleToggle', 'VimConsoleLog']
on_map = '<Plug>(vimconsole_'
hook_add = '''
  let g:vimconsole#auto_redraw = 1
  let g:vimconsole#height = 10
  let g:vimconsole#hooks = {}
  function! g:vimconsole#hooks.on_logged(context)
    call vimconsole#winopen()
  endfunction
'''

[[plugins]] # Beautiful indent of php and html.
repo = 'comeonly/php.vim-html-enhanced'
on_ft = ['php', 'html', 'xhtml']

[[plugins]] # To convert {range} mutually HTML and Entity.
repo = 'inotom/str2htmlentity'
on_cmd = ['Str2HtmlEntity', 'Entity2HtmlString']

[[plugins]]
repo = 'osyo-manga/vim-stargate'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'tkhren/vim-fake'
on_cmd = ['FakeSubstitute']
on_func = 'fake#'

[[plugins]] # Display unicode.
repo = 'osyo-manga/vim-hideout'
on_cmd = ['HideoutOn']

[[plugins]]
repo = 'lervag/vim-latex'
on_ft = ['tex', 'plaintex']

[[plugins]]
repo = 'xuhdev/vim-latex-live-preview'
on_ft = ['tex', 'plaintex']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'xhtml', 'css']
hook_add = '''
  let g:user_emmet_mode = 'iv'
  let g:user_emmet_expandabbr_key = '<c-y><c-y>'
'''

[[plugins]]
repo = 'rbtnn/game_engine.vim'
on_cmd = 'GameEngineStartGame'

[[plugins]]
repo = 'rbtnn/mario.vim'
depends = 'game_engine.vim'
on_cmd = 'Mario'

[[plugins]]
repo = 'rbtnn/puyo.vim'
depends = 'game_engine.vim'
on_cmd = 'Puyo'

[[plugins]]
repo = 'thinca/vim-threes'
on_cmd = ['ThreesStart', 'ThreesShowRecord']
hook_add = '''
  let g:threes#data_directory = expand('~/.vim/tmp')
  let g:threes#start_with_higher_tile = 1
  command! Threes ThreesStart
'''
